import { Injectable } from '@nestjs/common';
import { CreateCarDto } from './dto/create-car.dto';
import { UpdateCarDto } from './dto/update-car.dto';

export interface Car {
  id: number;
  brand: string;
  model: string;
  color: string;
  mileage: number;
  bodyType: string;
  year: number;
  isNew: boolean;
  city: string;
  transmission: string;
  seats: number;
  price: number;
  img: string;
}

export const cars: Car[] = [
  {
    id: 1,
    brand: "Mercedes-Benz",
    model: "G65 AMG",
    color: "Black",
    mileage: 10000,
    bodyType: "SUV",
    year: 2021,
    isNew: false,
    city: "Baku",
    transmission: "Automatic",
    seats: 5,
    price: 89990,
    img: "https://www.allcarz.ru/wp-content/uploads/2012/04/foto-mercedes-g65-amg_05-650x433.jpg",
  },
  {
    id: 2,
    brand: "BMW",
    model: "M5",
    color: "Blue",
    mileage: 5000,
    bodyType: "Sedan",
    year: 2022,
    isNew: true,
    city: "Moscow",
    transmission: "Automatic",
    seats: 5,
    price: 70000,
    img: "https://mngauto.lv/wp-content/uploads/2024/09/WhatsApp-Image-2024-09-12-at-10.51.20-scaled.jpeg",
  },
  {
    id: 3,
    brand: "Audi",
    model: "RS6",
    color: "Red",
    mileage: 12000,
    bodyType: "Wagon",
    year: 2021,
    isNew: false,
    city: "Kyiv",
    transmission: "Automatic",
    seats: 5,
    price: 150000,
    img: "https://avatars.mds.yandex.net/get-verba/1535139/2a0000016e6f6e476eb24bffe8980ddc7534/cattouchret",
  },
  {
    id: 4,
    brand: "Mercedes-Benz",
    model: "S600 V12",
    color: "White",
    mileage: 8000,
    bodyType: "Sedan",
    year: 2020,
    isNew: false,
    city: "Minsk",
    transmission: "Automatic",
    seats: 4,
    price: 118000,
    img: "https://avatars.mds.yandex.net/get-verba/1030388/2a000001609d0affd43f5ebe163cf57b0b6b/auto_main",
  },
  {
    id: 5,
    brand: "Mercedes-Benz",
    model: "C200",
    color: "Gray",
    mileage: 2000,
    bodyType: "Sedan",
    year: 2023,
    isNew: true,
    city: "Tbilisi",
    transmission: "Automatic",
    seats: 5,
    price: 101000,
    img: "https://mb-bel.ru/upload/img/5cc57461a20c2.jpeg",
  },
  {
    id: 6,
    brand: "Toyota",
    model: "Land Cruiser 300",
    color: "White",
    mileage: 0,
    bodyType: "SUV",
    year: 2024,
    isNew: true,
    city: "Dubai",
    transmission: "Automatic",
    seats: 7,
    price: 85000,
    img: "https://media.cdntoyota.co.za/toyotacms23/attachments/ckrq17ssi5cev0rqqxp368mnh-lc-300-front-34-ret-turned.desktop.jpg",
  },
  {
    id: 7,
    brand: "Lexus",
    model: "LX 570",
    color: "Black",
    mileage: 15000,
    bodyType: "SUV",
    year: 2019,
    isNew: false,
    city: "Astana",
    transmission: "Automatic",
    seats: 7,
    price: 78000,
    img: "https://www.motortrend.com/uploads/2023/01/2021-lexus-lx-570-three-quarter-front.jpg",
  },
  {
    id: 8,
    brand: "Porsche",
    model: "Panamera",
    color: "Blue",
    mileage: 3000,
    bodyType: "Liftback",
    year: 2023,
    isNew: true,
    city: "Berlin",
    transmission: "Automatic",
    seats: 4,
    price: 145000,
    img: "https://cdn.motor1.com/images/mgl/P33kYx/s3/2024-porsche-panamera.jpg",
  },
  {
    id: 9,
    brand: "Ferrari",
    model: "Roma",
    color: "Red",
    mileage: 1000,
    bodyType: "Coupe",
    year: 2024,
    isNew: true,
    city: "Rome",
    transmission: "Automatic",
    seats: 2,
    price: 220000,
    img: "https://robbreport.com/wp-content/uploads/2022/12/Ferrari-Roma-Spider.jpg",
  },
  {
    id: 10,
    brand: "Lamborghini",
    model: "Huracan",
    color: "Yellow",
    mileage: 4000,
    bodyType: "Coupe",
    year: 2022,
    isNew: false,
    city: "Dubai",
    transmission: "Robotized",
    seats: 2,
    price: 260000,
    img: "https://cdn.motor1.com/images/mgl/Q3MZb/s3/lamborghini-huracan-evo.jpg",
  },
  {
    id: 11,
    brand: "BMW",
    model: "X5",
    color: "Black",
    mileage: 6000,
    bodyType: "Crossover",
    year: 2021,
    isNew: false,
    city: "Warsaw",
    transmission: "Automatic",
    seats: 5,
    price: 82000,
    img: "https://cdn.motor1.com/images/mgl/ooXX3/s3/2024-bmw-x5.jpg",
  },
  {
    id: 12,
    brand: "Tesla",
    model: "Model S Plaid",
    color: "White",
    mileage: 500,
    bodyType: "Sedan",
    year: 2023,
    isNew: true,
    city: "California",
    transmission: "Electric",
    seats: 5,
    price: 130000,
    img: "https://cdn.motor1.com/images/mgl/KbBBX/s1/2022-tesla-model-s-plaid.jpg",
  },
  {
    id: 13,
    brand: "Rolls-Royce",
    model: "Phantom",
    color: "Black",
    mileage: 2000,
    bodyType: "Sedan",
    year: 2023,
    isNew: true,
    city: "London",
    transmission: "Automatic",
    seats: 4,
    price: 450000,
    img: "https://cdn.motor1.com/images/mgl/QeMMo/s3/2023-rolls-royce-phantom.jpg",
  },
  {
    id: 14,
    brand: "Bentley",
    model: "Continental GT",
    color: "Green",
    mileage: 3500,
    bodyType: "Coupe",
    year: 2022,
    isNew: false,
    city: "Paris",
    transmission: "Automatic",
    seats: 4,
    price: 320000,
    img: "https://cdn.motor1.com/images/mgl/ooYY3/s3/2024-bentley-continental-gt.jpg",
  },
  {
    id: 15,
    brand: "Toyota",
    model: "Camry",
    color: "White",
    mileage: 20000,
    bodyType: "Sedan",
    year: 2020,
    isNew: false,
    city: "Baku",
    transmission: "Automatic",
    seats: 5,
    price: 35000,
    img: "https://www.toyota.com/imgix/responsive/images/mlp/colorizer/2023/camry/1J9/1.png",
  },
  {
    id: 16,
    brand: "Kia",
    model: "Sportage",
    color: "Gray",
    mileage: 5000,
    bodyType: "Crossover",
    year: 2022,
    isNew: false,
    city: "Moscow",
    transmission: "Automatic",
    seats: 5,
    price: 29000,
    img: "https://cdn.motor1.com/images/mgl/VXXbO/s3/2023-kia-sportage.jpg",
  },
  {
    id: 17,
    brand: "Hyundai",
    model: "Sonata",
    color: "Blue",
    mileage: 10000,
    bodyType: "Sedan",
    year: 2021,
    isNew: false,
    city: "Tashkent",
    transmission: "Automatic",
    seats: 5,
    price: 27000,
    img: "https://cdn.motor1.com/images/mgl/ooZZ3/s3/2024-hyundai-sonata.jpg",
  },
  {
    id: 18,
    brand: "Chevrolet",
    model: "Tahoe",
    color: "Black",
    mileage: 12000,
    bodyType: "SUV",
    year: 2021,
    isNew: false,
    city: "Astana",
    transmission: "Automatic",
    seats: 7,
    price: 65000,
    img: "https://cdn.motor1.com/images/mgl/ooAA3/s3/2021-chevrolet-tahoe.jpg",
  },
  {
    id: 19,
    brand: "Nissan",
    model: "Patrol",
    color: "White",
    mileage: 15000,
    bodyType: "SUV",
    year: 2020,
    isNew: false,
    city: "Dubai",
    transmission: "Automatic",
    seats: 7,
    price: 60000,
    img: "https://cdn.motor1.com/images/mgl/LZZbO/s3/2023-nissan-patrol.jpg",
  },
  {
    id: 20,
    brand: "Mazda",
    model: "CX-9",
    color: "Red",
    mileage: 5000,
    bodyType: "Crossover",
    year: 2022,
    isNew: true,
    city: "Tokyo",
    transmission: "Automatic",
    seats: 7,
    price: 40000,
    img: "https://cdn.motor1.com/images/mgl/ZXXbO/s3/2023-mazda-cx-9.jpg",
  },
];


@Injectable()
export class CarsService {
  // create(createCarDto: CreateCarDto) {
  //   return 'This action adds a new car';
  // }

  findAll() {
    return cars;
  }

  findOne(id: number) {
    return cars.find(car => car.id === id);
  }

  // update(id: number, updateCarDto: UpdateCarDto) {
  //   return `This action updates a #${id} car`;
  // }

  // remove(id: number) {
  //   return `This action removes a #${id} car`;
  // }
}
